export const musics = [
	{
		name: 'Anjo Querubim',
		artist: 'Limão com Mel',
		imgSrc: 'images/musics/spencer-moore-1.jpg',
		href: '#',
	},
	{
		name: 'Me Usa',
		artist: 'Banda Magníficos',
		imgSrc: 'images/musics/spencer-moore-3.jpg',
		href: '#',
	},
	{
		name: 'A Praia',
		artist: 'Mastruz com Leite',
		imgSrc: 'images/musics/sean-o-riordan.jpg',
		href: '#',
	},
	{
		name: 'Tontos e Loucos',
		artist: 'Aviões do Forró',
		imgSrc: 'images/musics/carla-gomez-1.jpg',
		href: '#',
	},
	{
		name: 'Saga de um Vaqueiro',
		artist: 'Catuaba com Amendoim',
		imgSrc: 'images/musics/corwin-prescott-3.jpg',
		href: '#',
	},
	{
		name: 'Timidez',
		artist: 'Forró Cavalo de Pau',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Nosso Amor',
		artist: 'Lagosta Bronzeada',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Me Leva',
		artist: 'Alcymar Monteiro',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Xote das Meninas',
		artist: 'Luiz Gonzaga',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Chame Gente',
		artist: 'Dominguinhos',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Asa Branca',
		artist: 'Luiz Gonzaga',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Xote Nazaré',
		artist: 'Dominguinhos',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'No Rancho Fundo',
		artist: 'Luiz Gonzaga',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Beijinho Doce',
		artist: 'Elba Ramalho',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'Frevo Mulher',
		artist: 'Chico Buarque',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'De Volta pro Aconchego',
		artist: 'Alceu Valença',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
	{
		name: 'O Xote das Meninas',
		artist: 'Luiz Gonzaga',
		imgSrc: 'images/musics/card-image.png',
		href: '#',
	},
];
