export const tracks = [
	{
		title: 'A Praia',
		artist: 'Mastruz Com Leite',
		thumbnail: 'images/musics/aleks-eva-1.jpg',
		src: 'musics/Daryl Hall & John Oates - You Make My Dreams.mp3',
		href: '#',
	},
	{
		title: 'Me Usa',
		artist: 'Banda Magníficos',
		thumbnail: 'images/musics/carla-gomez-1.jpg',
		src: 'musics/Rod Stewart - Young Turks.mp3',
		href: '#',
	},
	{
		title: 'Anjo Querubim ',
		artist: 'Limão com Mel',
		thumbnail: 'images/musics/corwin-prescott-1.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'O brilho da lua',
		artist: 'Eliane do Forró',
		thumbnail: 'images/musics/corwin-prescott-2.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Tontos e loucos',
		artist: 'Aviões do Forró',
		thumbnail: 'images/musics/corwin-prescott-3.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Saga de um Vaqueiro',
		artist: 'Catuaba com Amendoim',
		thumbnail: 'images/musics/corwin-prescott-4.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Timidez',
		artist: 'Forró Cavalo de Pau',
		thumbnail: 'images/musics/corwin-prescott-5.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Nosso Amor ',
		artist: 'Lagosta Bronzeada',
		thumbnail: 'images/musics/eric-patterson-1.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Noda de Caju ',
		artist: 'Meu Vício',
		thumbnail: 'images/musics/eric-patterson-2.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Onde o Sonho Mora',
		artist: 'Calcinha Preta',
		thumbnail: 'images/musics/gordon-ross-1.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Planeta de Cores',
		artist: 'Forrozão Tropykália',
		thumbnail: 'images/musics/minkyeong-shin.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Xote da Alegria',
		artist: 'Falamansa',
		thumbnail: 'images/musics/mohammad-usaid-abbasi.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Blá Blá Blá',
		artist: 'Aviões do Forro',
		thumbnail: 'images/musics/nabil-george.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Zouk Do Rubi',
		artist: 'Forró Real',
		thumbnail: 'images/musics/nadeem-choudhary-2.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Brigas',
		artist: 'Banda Líbanos',
		thumbnail: 'images/musics/sean-o-riordan.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Todo Tempo É Pouco Pra Te Amar',
		artist: 'Brasas do Forró',
		thumbnail: 'images/musics/spencer-moore-1.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Eu sou estilo',
		artist: 'Garota Safada',
		thumbnail: 'images/musics/spencer-moore-3.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Me Beija',
		artist: 'Forró Real',
		thumbnail: 'images/musics/spencer-moore-4.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Faz um Coração Ai',
		artist: 'Banda Garota Safada',
		thumbnail: 'images/musics/zoltan-malovanyi.jpg',
		src: '',
		href: '#',
	},
	{
		title: 'Primeira vez ',
		artist: 'Forró dos Plays',
		thumbnail: 'images/musics/spencer-moore-2.jpg',
		src: '',
		href: '#',
	},
];
