// export const tracks = [
// 	{
// 		title: 'White Wedding',
// 		artist: 'Billy Idol',
// 		thumbnail: null,
// 		src: 'musics/Billy Idol - White Wedding.mp3',
// 	},
// 	{
// 		title: 'Smokin',
// 		artist: 'Boston',
// 		thumbnail: null,
// 		src: 'musics/Boston - Smokin.mp3',
// 	},
// 	{
// 		title: 'You Make My Dreams',
// 		artist: 'Daryl Hall & John Oates',
// 		thumbnail: null,
// 		src: 'musics/Daryl Hall & John Oates - You Make My Dreams.mp3',
// 	},
// 	{
// 		title: 'Two Tickets To Paradise',
// 		artist: 'Eddie Money',
// 		thumbnail: null,
// 		src: 'musics/Eddie Money - Two Tickets To Paradise.mp3',
// 	},
// 	{
// 		title: 'Some Kind of Wonderful',
// 		artist: 'Grand Funk Railroad',
// 		thumbnail: null,
// 		src: 'musics/Grand Funk Railroad - Some Kind of Wonderful.mp3',
// 	},
// 	{
// 		title: 'Get down to It',
// 		artist: 'Humble Pie',
// 		thumbnail: null,
// 		src: 'musics/Joe Cocker - Woman to woman.mp3',
// 	},
// 	{
// 		title: 'Woman to woman',
// 		artist: 'Joe Cocker',
// 		thumbnail: null,
// 		src: 'musics/KDST Humble Pie Get down to It.mp3',
// 	},
// 	{
// 		title: 'Strutter',
// 		artist: 'KISS',
// 		thumbnail: null,
// 		src: 'musics/KISS - Strutter.mp3',
// 	},
// 	{
// 		title: 'Young Turks',
// 		artist: 'Rod Stewart',
// 		thumbnail: null,
// 		src: 'musics/Rod Stewart - Young Turks.mp3',
// 	},
// 	{
// 		title: 'Runnin Down A Dream',
// 		artist: 'Tom Petty And The Heartbreakers',
// 		thumbnail: null,
// 		src: 'musics/Tom Petty And The Heartbreakers - Runnin Down A Dream.mp3',
// 	},
// 	{
// 		title: 'Hold The Line',
// 		artist: 'TOTO',
// 		thumbnail: null,
// 		src: 'musics/TOTO - Hold The Line.mp3',
// 	},
// ];

export const tracks = [
	{
		title: 'A Praia',
		artist: 'Mastruz Com Leite',
		thumbnail: 'images/musics/aleks-eva-1.jpg',
		src: 'musics/Daryl Hall & John Oates - You Make My Dreams.mp3',
	},
	{
		title: 'Me Usa',
		artist: 'Banda Magníficos',
		thumbnail: 'images/musics/carla-gomez-1.jpg',
		src: 'musics/Rod Stewart - Young Turks.mp3',
	},
	{
		title: 'Anjo Querubim ',
		artist: 'Limão com Mel',
		thumbnail: 'images/musics/corwin-prescott-1.jpg',
		src: 'musics/Billy Idol - White Wedding.mp3',
	},
	{
		title: 'O brilho da lua',
		artist: 'Eliane do Forró',
		thumbnail: 'images/musics/corwin-prescott-2.jpg',
		src: 'musics/Boston - Smokin.mp3',
	},
	{
		title: 'Tontos e loucos',
		artist: 'Aviões do Forró',
		thumbnail: 'images/musics/corwin-prescott-3.jpg',
		src: 'musics/Eddie Money - Two Tickets To Paradise.mp3',
	},
	{
		title: 'Saga de um Vaqueiro',
		artist: 'Catuaba com Amendoim',
		thumbnail: 'images/musics/corwin-prescott-4.jpg',
		src: 'musics/Grand Funk Railroad - Some Kind of Wonderful.mp3',
	},
	{
		title: 'Timidez',
		artist: 'Forró Cavalo de Pau',
		thumbnail: 'images/musics/corwin-prescott-5.jpg',
		src: 'musics/Joe Cocker - Woman to woman.mp3',
	},
	{
		title: 'Nosso Amor ',
		artist: 'Lagosta Bronzeada',
		thumbnail: 'images/musics/eric-patterson-1.jpg',
		src: 'musics/Humble Pie - Get down to It.mp3',
	},
	{
		title: 'Noda de Caju ',
		artist: 'Meu Vício',
		thumbnail: 'images/musics/eric-patterson-2.jpg',
		src: 'musics/KISS - Strutter.mp3',
	},
	{
		title: 'Onde o Sonho Mora',
		artist: 'Calcinha Preta',
		thumbnail: 'images/musics/gordon-ross-1.jpg',
		src: 'musics/Tom Petty And The Heartbreakers - Runnin Down A Dream.mp3',
	},
	{
		title: 'Planeta de Cores',
		artist: 'Forrozão Tropykália',
		thumbnail: 'images/musics/minkyeong-shin.jpg',
		src: 'musics/TOTO - Hold The Line.mp3',
	},
	{
		title: 'Xote da Alegria',
		artist: 'Falamansa',
		thumbnail: 'images/musics/mohammad-usaid-abbasi.jpg',
		src: '',
	},
	{
		title: 'Blá Blá Blá',
		artist: 'Aviões do Forro',
		thumbnail: 'images/musics/nabil-george.jpg',
		src: '',
	},
	{
		title: 'Zouk Do Rubi',
		artist: 'Forró Real',
		thumbnail: 'images/musics/nadeem-choudhary-2.jpg',
		src: '',
	},
	{
		title: 'Brigas',
		artist: 'Banda Líbanos',
		thumbnail: 'images/musics/sean-o-riordan.jpg',
		src: '',
	},
	{
		title: 'Todo Tempo É Pouco Pra Te Amar',
		artist: 'Brasas do Forró',
		thumbnail: 'images/musics/spencer-moore-1.jpg',
		src: '',
	},
	{
		title: 'Eu sou estilo',
		artist: 'Garota Safada',
		thumbnail: 'images/musics/spencer-moore-3.jpg',
		src: '',
	},
	{
		title: 'Me Beija',
		artist: 'Forró Real',
		thumbnail: 'images/musics/spencer-moore-4.jpg',
		src: '',
	},
	{
		title: 'Faz um Coração Ai',
		artist: 'Banda Garota Safada',
		thumbnail: 'images/musics/zoltan-malovanyi.jpg',
		src: '',
	},
	{
		title: 'Primeira vez ',
		artist: 'Forró dos Plays',
		thumbnail: 'images/musics/spencer-moore-2.jpg',
		src: '',
	},
];
